name: "Coverage Compare"
description: "Greet someone and record the time"
inputs:
  github-token:
    description: "The github token"
    required: false
    default: ${{ github.token }}
  base-coverage-file:
    description: "Path to Base Coverage file"
    required: true
  current-coverage-file:
    description: "Path to Current Coverage file"
    required: true
  app-root:
    description: "The common root path of the files to snip from the filename (optional, useful for monorepos)"
    required: false
    default: ""
  comment-header:
    description: "The header for the comment (optional, only required if this will be run for multiple comparisons in a single PR)"
    required: false
    default: "Coverage Comparison"
  comment-on-no-changes:
    description: "If true, will always comment, even if there were no changes in coverage (optional, defaults to false)"
    required: false
    default: false
runs:
  using: "node12"
  main: "dist/index.js"
